### ISSUE TITLE
how to  save image returned from img = api.photo.random() function

### ISSUE THREAD

**Issue by jaykeerti** [yakupadakli/python-unsplash#7]
from unsplash.api import Api
from unsplash.auth import Auth

client_id = ""
client_secret = ""
redirect_uri = ""
code = ""

auth = Auth(client_id, client_secret, redirect_uri, code=code)
api = Api(auth)
img = api.photo.random()

How to save the image which is returned as **[Photo(id='Lg9uUduhSrc')]**

**Comment by atharvakadlag** [comment]
did you get the solution?
